backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
public_folder: "/src/images/" # Adjust the path to be relative to the static folder

collections:
  - name: "notice"
    label: "Notice"
    folder: "content/notice"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "PDF File", name: "pdf", widget: "file" }
